### PR TITLE
Simplify exporter UI

### PR DESCRIPTION
**Pull request by vadi2**
This is a no pop-ups dialog unlike the previous workflow. Mockup:

module exporter - preview _245

Explanation of the new UI: https://streamable.com/omyw6

Have a look, let me know what you think. I think the proposal is a lot simpler to work with than what we've got right now. Less knobs and you can get stuff done faster.

### CODE REVIEW

**Comment by SlySven** [comment]
Um, you have removed two `QDialogButtons` (Reset and Cancel) that were important to the flow of execution in my code - the `Cancel` was needed to abort the process __before__ exportation was performed and the `Reset` button is re-purposed as the "Select files to include" (or in my case only open a file dialog centered on the _temporary_ staging area - in your case it will need to change to be a select multiple-files/directories dialogue though that is perfectly do-able).  The "Close" button was, in my code, only enabled __after__ the export was attempted because it was needed to enable the dialogue to display the success/fail message for the user before they explicitly told the dialogue to close with it.  Also you have removed the `(QLabel) textLabel_exportLocation` from the form/dialogue (because you have replaced it with a `(QPushButton) pushButton_2` which bares the text "Select Export Location") but you need to remove the pair of `show()`/`hide()` calls in `dlgPackageExporter.cpp` as that is causing the current compile failures... 😉

On the whole the proposal looks interesting - I am just thinking about our current implementation and how it can be transformed into this - some of my pondering includes:

Each (archive file format) package that is _installed_ is unpackaged into a sub-directory beneath the profile's _home_ one - and that is not edited or modified by any actions the user might make before this package/module exporter is gotten involved.  This is separate from the _temporary, staging_ area which prior to my PR attempt was not temporary at all it just sat in the `packageName` sub-directory of the `tmp` sub-directory of the profile's home directory - now it _can_ be, but to avoid breakage is not by default.  As it was not actually temporary _in the past_ this meant that a fresh invocation with __the same packageName__ would auto-magically gain all the extra _resources_ that the user had previously gathered.  I guess it would be fine for your PR to just clone them from the currently expanded instance - unless it is a common thing that real-life packages create new content in the directory into which they are expanded when used - then it might be more awkward not to keep the directory tree where the package/module resources are assembled as a separate location (under the `profileHome/tmp/packageName` one).

If we are going to make it easier for the user to reiterate through the package creation process we ought to add additional stuff to the `config.lua` file so they can include at least __version__ information, I'd also suggest __author__ , __email__, __URL__, __creation dateTimeStamp__ and, given that the packages might be modified and _synced_, a separate __lastSavedDateTimeStamp__ and/or a __saved (or synced) times__ count {so the user can tell the difference between two similar looking package files with the same name}; my current PR has space for that to be added when the package name is asked for but you might consider an additional "pop-up" to request (some) of those details in a similar way as I have done with a "Package Details" (or "Module Details" 😜 ) button at the bottom of the "Name your package" `QGroupBox`.  As a nicety for at least *nix users adding the details to be kept in the `config.lua` also as an archive comment into the zip file (with `zip_set_archive_comment(...)`) it means that a command line inspection of the `.zip`/`.mpackage` file with `unzip -l` gives useful information on the command line - e.g. like from a previous (abandoned attempt on the package manager):
screenshot_20171119_175521

Anyhow - I await to see how the glue to make this new dialogue work, works out...

**Comment by vadi2** [comment]
There is no point to having `Cancel` - it'll have the same outcome as `Close`. `Close` should be always enabled so you aren't forced to export before closing the dialog. Exporting no longer automatically closes.

I'm not interested in adding more things to `config.lua` at this point in time, there hasn't been a need for it. Let's do this one step at a time.

**Comment by SlySven** [comment]
> There is no point to having Cancel - it'll have the same outcome as Close. Close should be always enabled so you aren't forced to export before closing the dialog. Exporting no longer automatically closes.

Of course, yeah I hadn't spotted that. 🤦‍♂️

**Comment by vadi2** [comment]
How did you want to proceed with this? I've created the mockup of how the UI ought to be but I don't have the bandwidth to take on coding it in now too.

**Comment by SlySven** [comment]
Well, I could try and clean up what I have so far which now works (unlike the past code with _any_ sub-directories of _other_ files) and merge the cancel/close button functionality - and revisit overhauling the UX in the future.

**Comment by vadi2** [comment]
It does work but by adding more switches and toggles to what already is not an intuitive export process it complicates the whole thing even more, and that puts people off.

Nonetheless, fixing inclusion of the nested resources is a welcome change so let's proceed with it for the time being and I'll dedicate time to rewriting the whole thing at a later point.

**Comment by Kebap** [comment]
This seems way nicer indeed!

**Comment by Kebap** [comment]
As discussed with Vadi, this PR is outdated and can be closed, will be discussed further in #2675 linked above.

**Pull request closed without merging**
